// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_Example_UI

#ifndef _SQUARELINE_PROJECT_EXAMPLE_UI_UI_H
#define _SQUARELINE_PROJECT_EXAMPLE_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Main_Label1;
void ui_event_Main_Button1(lv_event_t * e);
extern lv_obj_t * ui_Main_Button1;
extern lv_obj_t * ui_Main_Label2;
void ui_event_Main_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Main_Slider1;
extern lv_obj_t * ui_Main_Label3;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
