// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_Example_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main(lv_event_t * e);
lv_obj_t * ui_Main;
lv_obj_t * ui_Main_Label1;
void ui_event_Main_Button1(lv_event_t * e);
lv_obj_t * ui_Main_Button1;
lv_obj_t * ui_Main_Label2;
void ui_event_Main_Slider1(lv_event_t * e);
lv_obj_t * ui_Main_Slider1;
lv_obj_t * ui_Main_Label3;


// SCREEN: ui_PPM
void ui_PPM_screen_init(void);
void ui_event_PPM(lv_event_t * e);
lv_obj_t * ui_PPM;
lv_obj_t * ui_PPM_Label1;
lv_obj_t * ui_PPM_Label2;
lv_obj_t * ui_PPM_Label3;


// SCREEN: ui_SDcard
void ui_SDcard_screen_init(void);
void ui_event_SDcard(lv_event_t * e);
lv_obj_t * ui_SDcard;
lv_obj_t * ui_SDcardTitle;
lv_obj_t * ui_SDcardTitle2;
lv_obj_t * ui_SDcard_Label6;


// SCREEN: ui_RTC
void ui_RTC_screen_init(void);
void ui_event_RTC(lv_event_t * e);
lv_obj_t * ui_RTC;
lv_obj_t * ui_RTCTitle1;
lv_obj_t * ui_RTCTitle3;
lv_obj_t * ui_RTCtimeLabel;
lv_obj_t * ui_RTC_Calendar;
void ui_event_RTC_Button1(lv_event_t * e);
lv_obj_t * ui_RTC_Button1;
lv_obj_t * ui_RTC_Label1;
lv_obj_t * ui_RTC_Date_Label;


// SCREEN: ui_Set_Time
void ui_Set_Time_screen_init(void);
void ui_event_Set_Time(lv_event_t * e);
lv_obj_t * ui_Set_Time;
lv_obj_t * ui_Set_Time_TabView1;
lv_obj_t * ui_Set_Time_Time;
void ui_event_Set_Time_Button(lv_event_t * e);
lv_obj_t * ui_Set_Time_Button;
lv_obj_t * ui_RTC_Label2;
lv_obj_t * ui_Set_Time_Roller_Hour;
lv_obj_t * ui_Set_Time_Roller_Minute;
lv_obj_t * ui_Set_Time_Roller_AMPM;
lv_obj_t * ui_Set_Time_Date;
lv_obj_t * ui_Set_Time_Roller_Day;
void ui_event_Set_Time_Roller_Month(lv_event_t * e);
lv_obj_t * ui_Set_Time_Roller_Month;
void ui_event_Set_Time_Roller_Year(lv_event_t * e);
lv_obj_t * ui_Set_Time_Roller_Year;
void ui_event_Set_Date_Button(lv_event_t * e);
lv_obj_t * ui_Set_Date_Button;
lv_obj_t * ui_RTC_Label3;
lv_obj_t * ui_RTCTitle4;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_PPM, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_PPM_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_RTC, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_RTC_screen_init);
    }
}
void ui_event_Main_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_event_cb(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        main_screen_button_long_pressed(e);
    }
}
void ui_event_Main_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Main_Label3, target, "", "");
    }
}
void ui_event_PPM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Main_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SDcard, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_SDcard_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        setPPMlabel(e);
    }
}
void ui_event_SDcard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_PPM, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_PPM_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_RTC, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_RTC_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        sdcard_screen_loaded(e);
    }
}
void ui_event_RTC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SDcard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_SDcard_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Main_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        update_time_and_date_to_screen(e);
    }
}
void ui_event_RTC_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Set_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Set_Time_screen_init);
    }
}
void ui_event_Set_Time(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        select_time_and_date_rollers(e);
    }
}
void ui_event_Set_Time_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        set_time_manually(e);
    }
}
void ui_event_Set_Time_Roller_Month(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        date_changed(e);
    }
}
void ui_event_Set_Time_Roller_Year(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        date_changed(e);
    }
}
void ui_event_Set_Date_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Set_Date_Manually(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui_PPM_screen_init();
    ui_SDcard_screen_init();
    ui_RTC_screen_init();
    ui_Set_Time_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
