// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_Example_UI

#ifndef _SQUARELINE_PROJECT_EXAMPLE_UI_UI_H
#define _SQUARELINE_PROJECT_EXAMPLE_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main(lv_event_t * e);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Main_Label1;
void ui_event_Main_Button1(lv_event_t * e);
extern lv_obj_t * ui_Main_Button1;
extern lv_obj_t * ui_Main_Label2;
void ui_event_Main_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Main_Slider1;
extern lv_obj_t * ui_Main_Label3;
// SCREEN: ui_PPM
void ui_PPM_screen_init(void);
void ui_event_PPM(lv_event_t * e);
extern lv_obj_t * ui_PPM;
extern lv_obj_t * ui_PPM_Label1;
extern lv_obj_t * ui_PPM_Label2;
extern lv_obj_t * ui_PPM_Label3;
// SCREEN: ui_SDcard
void ui_SDcard_screen_init(void);
void ui_event_SDcard(lv_event_t * e);
extern lv_obj_t * ui_SDcard;
extern lv_obj_t * ui_SDcardTitle;
extern lv_obj_t * ui_SDcardTitle2;
extern lv_obj_t * ui_SDcard_Label6;
// SCREEN: ui_RTC
void ui_RTC_screen_init(void);
void ui_event_RTC(lv_event_t * e);
extern lv_obj_t * ui_RTC;
extern lv_obj_t * ui_RTCTitle1;
extern lv_obj_t * ui_RTCTitle3;
extern lv_obj_t * ui_RTCtimeLabel;
extern lv_obj_t * ui_RTC_Calendar;
void ui_event_RTC_Button1(lv_event_t * e);
extern lv_obj_t * ui_RTC_Button1;
extern lv_obj_t * ui_RTC_Label1;
extern lv_obj_t * ui_RTC_Date_Label;
// SCREEN: ui_Set_Time
void ui_Set_Time_screen_init(void);
void ui_event_Set_Time(lv_event_t * e);
extern lv_obj_t * ui_Set_Time;
extern lv_obj_t * ui_Set_Time_TabView1;
extern lv_obj_t * ui_Set_Time_Time;
void ui_event_Set_Time_Button(lv_event_t * e);
extern lv_obj_t * ui_Set_Time_Button;
extern lv_obj_t * ui_RTC_Label2;
extern lv_obj_t * ui_Set_Time_Roller_Hour;
extern lv_obj_t * ui_Set_Time_Roller_Minute;
extern lv_obj_t * ui_Set_Time_Roller_AMPM;
extern lv_obj_t * ui_Set_Time_Date;
extern lv_obj_t * ui_Set_Time_Roller_Day;
void ui_event_Set_Time_Roller_Month(lv_event_t * e);
extern lv_obj_t * ui_Set_Time_Roller_Month;
void ui_event_Set_Time_Roller_Year(lv_event_t * e);
extern lv_obj_t * ui_Set_Time_Roller_Year;
void ui_event_Set_Date_Button(lv_event_t * e);
extern lv_obj_t * ui_Set_Date_Button;
extern lv_obj_t * ui_RTC_Label3;
extern lv_obj_t * ui_RTCTitle4;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
