// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_Example_UI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void btn_event_cb(lv_event_t * e);
void setPPMlabel(lv_event_t * e);
void sdcard_screen_loaded(lv_event_t * e);
void update_time_and_date_to_screen(lv_event_t * e);
void select_time_and_date_rollers(lv_event_t * e);
void set_time_manually(lv_event_t * e);
void date_changed(lv_event_t * e);
void Set_Date_Manually(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
