// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_Example_UI

#include "../ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_Label1 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Main_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_Label1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Main_Label1, "SQUARELINE \nSTUDIO DEMO");
    lv_obj_set_style_text_align(ui_Main_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_Label1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Button1 = lv_btn_create(ui_Main);
    lv_obj_set_width(ui_Main_Button1, 200);
    lv_obj_set_height(ui_Main_Button1, 100);
    lv_obj_set_x(ui_Main_Button1, 20);
    lv_obj_set_y(ui_Main_Button1, 100);
    lv_obj_add_flag(ui_Main_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Main_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_Label2 = lv_label_create(ui_Main_Button1);
    lv_obj_set_width(ui_Main_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Label2, "Button");
    lv_obj_set_style_text_font(ui_Main_Label2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Slider1 = lv_slider_create(ui_Main);
    lv_slider_set_value(ui_Main_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Main_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Main_Slider1, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_Main_Slider1, 200);
    lv_obj_set_height(ui_Main_Slider1, 10);
    lv_obj_set_align(ui_Main_Slider1, LV_ALIGN_CENTER);


    ui_Main_Label3 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Main_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_Label3, 0);
    lv_obj_set_y(ui_Main_Label3, -25);
    lv_obj_set_align(ui_Main_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Label3, "0");
    lv_obj_set_style_text_font(ui_Main_Label3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Main_Button1, ui_event_Main_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_Slider1, ui_event_Main_Slider1, LV_EVENT_ALL, NULL);

}
