// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_Example_UI

#include "../ui.h"

void ui_PPM_screen_init(void)
{
    ui_PPM = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PPM_Label1 = lv_label_create(ui_PPM);
    lv_obj_set_width(ui_PPM_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPM_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PPM_Label1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_PPM_Label1, "AMOLED PLUS \nDEMO");
    lv_obj_set_style_text_align(ui_PPM_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PPM_Label1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPM_Label2 = lv_label_create(ui_PPM);
    lv_obj_set_width(ui_PPM_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPM_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPM_Label2, 0);
    lv_obj_set_y(ui_PPM_Label2, -175);
    lv_obj_set_align(ui_PPM_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPM_Label2, "PPM");
    lv_obj_set_style_text_decor(ui_PPM_Label2, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PPM_Label2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPM_Label3 = lv_label_create(ui_PPM);
    lv_obj_set_width(ui_PPM_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPM_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPM_Label3, 0);
    lv_obj_set_y(ui_PPM_Label3, lv_pct(10));
    lv_obj_set_align(ui_PPM_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPM_Label3, "Charge Status");
    lv_label_set_recolor(ui_PPM_Label3, "true");
    lv_obj_set_style_text_align(ui_PPM_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PPM_Label3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PPM, ui_event_PPM, LV_EVENT_ALL, NULL);

}
