// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_Example_UI

#include "../ui.h"

void ui_RTC_screen_init(void)
{
    ui_RTC = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RTC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RTCTitle1 = lv_label_create(ui_RTC);
    lv_obj_set_width(ui_RTCTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RTCTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RTCTitle1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_RTCTitle1, "AMOLED PLUS \nDEMO");
    lv_obj_set_style_text_align(ui_RTCTitle1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RTCTitle1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RTCTitle3 = lv_label_create(ui_RTC);
    lv_obj_set_width(ui_RTCTitle3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RTCTitle3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RTCTitle3, 0);
    lv_obj_set_y(ui_RTCTitle3, -175);
    lv_obj_set_align(ui_RTCTitle3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RTCTitle3, "RTC");
    lv_obj_set_style_text_decor(ui_RTCTitle3, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RTCTitle3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RTCtimeLabel = lv_label_create(ui_RTC);
    lv_obj_set_width(ui_RTCtimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RTCtimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RTCtimeLabel, 0);
    lv_obj_set_y(ui_RTCtimeLabel, -40);
    lv_obj_set_align(ui_RTCtimeLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_RTCtimeLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_RTCtimeLabel, "12:34 AM");
    lv_label_set_recolor(ui_RTCtimeLabel, "true");
    lv_obj_set_style_text_font(ui_RTCtimeLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RTC_Calendar = lv_calendar_create(ui_RTC);
    lv_calendar_set_today_date(ui_RTC_Calendar, 2025, 1, 1);
    lv_calendar_set_showed_date(ui_RTC_Calendar, 2025, 1);
    lv_obj_t * ui_RTC_Calendar_header = lv_calendar_header_arrow_create(ui_RTC_Calendar);
    lv_obj_set_height(ui_RTC_Calendar, 240);
    lv_obj_set_width(ui_RTC_Calendar, lv_pct(95));
    lv_obj_set_x(ui_RTC_Calendar, 0);
    lv_obj_set_y(ui_RTC_Calendar, -2);
    lv_obj_set_align(ui_RTC_Calendar, LV_ALIGN_BOTTOM_MID);

    ui_RTC_Button1 = lv_btn_create(ui_RTC);
    lv_obj_set_width(ui_RTC_Button1, lv_pct(75));
    lv_obj_set_height(ui_RTC_Button1, lv_pct(15));
    lv_obj_set_x(ui_RTC_Button1, 0);
    lv_obj_set_y(ui_RTC_Button1, lv_pct(-21));
    lv_obj_set_align(ui_RTC_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RTC_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RTC_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_RTC_Button1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RTC_Label1 = lv_label_create(ui_RTC_Button1);
    lv_obj_set_width(ui_RTC_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RTC_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RTC_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RTC_Label1, "SET");
    lv_obj_set_style_text_font(ui_RTC_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RTC_Date_Label = lv_label_create(ui_RTC);
    lv_obj_set_width(ui_RTC_Date_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RTC_Date_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RTC_Date_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RTC_Date_Label, "00/00/0000");
    lv_obj_set_style_text_font(ui_RTC_Date_Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_RTC_Button1, ui_event_RTC_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RTC, ui_event_RTC, LV_EVENT_ALL, NULL);

}
