// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_Example_UI

#include "../ui.h"

void ui_Set_Time_screen_init(void)
{
    ui_Set_Time = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Set_Time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Set_Time_TabView1 = lv_tabview_create(ui_Set_Time, LV_DIR_BOTTOM, 75);
    lv_obj_set_width(ui_Set_Time_TabView1, lv_pct(100));
    lv_obj_set_height(ui_Set_Time_TabView1, lv_pct(100));
    lv_obj_set_align(ui_Set_Time_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Set_Time_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Set_Time_TabView1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Set_Time_Time = lv_tabview_add_tab(ui_Set_Time_TabView1, "Time");

    ui_Set_Time_Button = lv_btn_create(ui_Set_Time_Time);
    lv_obj_set_width(ui_Set_Time_Button, lv_pct(80));
    lv_obj_set_height(ui_Set_Time_Button, lv_pct(20));
    lv_obj_set_x(ui_Set_Time_Button, -1);
    lv_obj_set_y(ui_Set_Time_Button, lv_pct(-40));
    lv_obj_set_align(ui_Set_Time_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Set_Time_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Set_Time_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Set_Time_Button, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RTC_Label2 = lv_label_create(ui_Set_Time_Button);
    lv_obj_set_width(ui_RTC_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RTC_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RTC_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RTC_Label2, "SET");
    lv_obj_set_style_text_font(ui_RTC_Label2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Set_Time_Roller_Hour = lv_roller_create(ui_Set_Time_Time);
    lv_roller_set_options(ui_Set_Time_Roller_Hour, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Set_Time_Roller_Hour, 5, LV_ANIM_OFF);
    lv_obj_set_width(ui_Set_Time_Roller_Hour, lv_pct(30));
    lv_obj_set_height(ui_Set_Time_Roller_Hour, lv_pct(75));
    lv_obj_set_x(ui_Set_Time_Roller_Hour, -70);
    lv_obj_set_y(ui_Set_Time_Roller_Hour, lv_pct(10));
    lv_obj_set_align(ui_Set_Time_Roller_Hour, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Set_Time_Roller_Hour, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Set_Time_Roller_Hour, &lv_font_montserrat_40, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Set_Time_Roller_Minute = lv_roller_create(ui_Set_Time_Time);
    lv_roller_set_options(ui_Set_Time_Roller_Minute,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Set_Time_Roller_Minute, 30, LV_ANIM_OFF);
    lv_obj_set_width(ui_Set_Time_Roller_Minute, lv_pct(30));
    lv_obj_set_height(ui_Set_Time_Roller_Minute, lv_pct(75));
    lv_obj_set_x(ui_Set_Time_Roller_Minute, lv_pct(0));
    lv_obj_set_y(ui_Set_Time_Roller_Minute, lv_pct(10));
    lv_obj_set_align(ui_Set_Time_Roller_Minute, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Set_Time_Roller_Minute, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Set_Time_Roller_Minute, &lv_font_montserrat_40, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Set_Time_Roller_AMPM = lv_roller_create(ui_Set_Time_Time);
    lv_roller_set_options(ui_Set_Time_Roller_AMPM, "AM\nPM", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Set_Time_Roller_AMPM, lv_pct(30));
    lv_obj_set_height(ui_Set_Time_Roller_AMPM, lv_pct(40));
    lv_obj_set_x(ui_Set_Time_Roller_AMPM, 70);
    lv_obj_set_y(ui_Set_Time_Roller_AMPM, lv_pct(10));
    lv_obj_set_align(ui_Set_Time_Roller_AMPM, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Set_Time_Roller_AMPM, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Set_Time_Roller_AMPM, &lv_font_montserrat_40, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Set_Time_Date = lv_tabview_add_tab(ui_Set_Time_TabView1, "Date");

    ui_Set_Time_Roller_Day = lv_roller_create(ui_Set_Time_Date);
    lv_roller_set_options(ui_Set_Time_Roller_Day,
                          "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Set_Time_Roller_Day, 11, LV_ANIM_OFF);
    lv_obj_set_width(ui_Set_Time_Roller_Day, lv_pct(30));
    lv_obj_set_height(ui_Set_Time_Roller_Day, lv_pct(75));
    lv_obj_set_x(ui_Set_Time_Roller_Day, -70);
    lv_obj_set_y(ui_Set_Time_Roller_Day, lv_pct(10));
    lv_obj_set_align(ui_Set_Time_Roller_Day, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Set_Time_Roller_Day, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Set_Time_Roller_Day, &lv_font_montserrat_40, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Set_Time_Roller_Month = lv_roller_create(ui_Set_Time_Date);
    lv_roller_set_options(ui_Set_Time_Roller_Month, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Set_Time_Roller_Month, 5, LV_ANIM_OFF);
    lv_obj_set_width(ui_Set_Time_Roller_Month, lv_pct(30));
    lv_obj_set_height(ui_Set_Time_Roller_Month, lv_pct(75));
    lv_obj_set_x(ui_Set_Time_Roller_Month, 0);
    lv_obj_set_y(ui_Set_Time_Roller_Month, lv_pct(10));
    lv_obj_set_align(ui_Set_Time_Roller_Month, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Set_Time_Roller_Month, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Set_Time_Roller_Month, &lv_font_montserrat_40, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Set_Time_Roller_Year = lv_roller_create(ui_Set_Time_Date);
    lv_roller_set_options(ui_Set_Time_Roller_Year, "25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Set_Time_Roller_Year, lv_pct(30));
    lv_obj_set_height(ui_Set_Time_Roller_Year, lv_pct(75));
    lv_obj_set_x(ui_Set_Time_Roller_Year, 70);
    lv_obj_set_y(ui_Set_Time_Roller_Year, lv_pct(10));
    lv_obj_set_align(ui_Set_Time_Roller_Year, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Set_Time_Roller_Year, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Set_Time_Roller_Year, &lv_font_montserrat_40, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Set_Date_Button = lv_btn_create(ui_Set_Time_Date);
    lv_obj_set_width(ui_Set_Date_Button, lv_pct(80));
    lv_obj_set_height(ui_Set_Date_Button, lv_pct(20));
    lv_obj_set_x(ui_Set_Date_Button, 0);
    lv_obj_set_y(ui_Set_Date_Button, lv_pct(-40));
    lv_obj_set_align(ui_Set_Date_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Set_Date_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Set_Date_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Set_Date_Button, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RTC_Label3 = lv_label_create(ui_Set_Date_Button);
    lv_obj_set_width(ui_RTC_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RTC_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RTC_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RTC_Label3, "SET");
    lv_obj_set_style_text_font(ui_RTC_Label3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RTCTitle4 = lv_label_create(ui_Set_Time_TabView1);
    lv_obj_set_width(ui_RTCTitle4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RTCTitle4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RTCTitle4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_RTCTitle4, "AMOLED PLUS \nDEMO");
    lv_obj_set_style_text_align(ui_RTCTitle4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RTCTitle4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Set_Time_Button, ui_event_Set_Time_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Set_Time_Roller_Month, ui_event_Set_Time_Roller_Month, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Set_Time_Roller_Year, ui_event_Set_Time_Roller_Year, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Set_Date_Button, ui_event_Set_Date_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Set_Time, ui_event_Set_Time, LV_EVENT_ALL, NULL);

}
