// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_Example_UI

#include "../ui.h"

void ui_SDcard_screen_init(void)
{
    ui_SDcard = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SDcard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SDcardTitle = lv_label_create(ui_SDcard);
    lv_obj_set_width(ui_SDcardTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SDcardTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SDcardTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SDcardTitle, "AMOLED PLUS \nDEMO");
    lv_obj_set_style_text_align(ui_SDcardTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SDcardTitle, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SDcardTitle2 = lv_label_create(ui_SDcard);
    lv_obj_set_width(ui_SDcardTitle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SDcardTitle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SDcardTitle2, 0);
    lv_obj_set_y(ui_SDcardTitle2, -175);
    lv_obj_set_align(ui_SDcardTitle2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SDcardTitle2, "SD Card");
    lv_obj_set_style_text_decor(ui_SDcardTitle2, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SDcardTitle2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SDcard_Label6 = lv_label_create(ui_SDcard);
    lv_obj_set_width(ui_SDcard_Label6, lv_pct(100));
    lv_obj_set_height(ui_SDcard_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SDcard_Label6, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_SDcard_Label6, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_SDcard_Label6, "SD Card Detected");
    lv_label_set_recolor(ui_SDcard_Label6, "true");
    lv_obj_set_style_text_align(ui_SDcard_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SDcard_Label6, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SDcard, ui_event_SDcard, LV_EVENT_ALL, NULL);

}
